# Generated by Django 3.0.7 on 2022-10-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('diet', 'Diet')], default='exercise', max_length=50),
        ),
    ]
